Set.add(), ivrTotalSeconds -> ivrTimeSeconds, and migrating to signature_hash">
import { supabase } from './supabase';
import type { AgentStatusRecord, AgentStatusUpload, CallRecord, CallRecordInsert, CallUpload, DeduplicationStats, ProcessedCallSignature } from './supabase';
import type { ParsedCallRecord } from './csvParser';
import { hashPhone, maskPhone, filterOverlappingCalls, generateCallSignature } from './csvParser';
import type { AgentStatusRow } from './agentStatusParser';

const BATCH_SIZE = 500;

// ============================================================================
// CALL RECORDS
// ============================================================================

export async function getAllCallRecords(): Promise<CallRecord[]> {
  const { data, error } = await supabase
    .from('call_records')
    .select('*')
    .order('call_date', { ascending: false });

  if (error) {
    console.error('Error fetching call records:', error);
    throw error;
  }

  return data || [];
}

export async function getCallRecordsByUpload(uploadId: string): Promise<CallRecord[]> {
  const { data, error } = await supabase
    .from('call_records')
    .select('*')
    .eq('upload_id', uploadId)
    .order('call_date', { ascending: false });

  if (error) {
    console.error('Error fetching call records by upload:', error);
    throw error;
  }

  return data || [];
}

// ============================================================================
// UPLOADS
// ============================================================================

export async function getAllUploads(): Promise<CallUpload[]> {
  const { data, error } = await supabase
    .from('call_uploads')
    .select('*')
    .order('uploaded_at', { ascending: false });

  if (error) {
    console.error('Error fetching uploads:', error);
    throw error;
  }

  return data || [];
}

export async function saveUpload(
  filename: string,
  records: ParsedCallRecord[]
): Promise<{ upload: CallUpload; savedCount: number; stats: DeduplicationStats }> {
  if (records.length === 0) {
    throw new Error('No records to save');
  }

  // Calculate date range
  const dates = records
    .map(r => r.callDate)
    .filter((d): d is string => !!d)
    .sort();
  
  const dateRangeStart = dates[0] || null;
  const dateRangeEnd = dates[dates.length - 1] || null;

  // Create upload record
  const { data: uploadData, error: uploadError } = await supabase
    .from('call_uploads')
    .insert({
      filename,
      record_count: records.length,
      date_range_start: dateRangeStart,
      date_range_end: dateRangeEnd,
    })
    .select()
    .single();

  if (uploadError || !uploadData) {
    console.error('Error creating upload:', uploadError);
    throw uploadError || new Error('Failed to create upload');
  }

  const upload = uploadData as CallUpload;

  // Process records with deduplication and overlapping detection
  const processedSignatures = await getProcessedSignatures();
  const { records: markedRecords, canceledCount } = filterOverlappingCalls(records);

  // Filter out duplicates
  const newRecords: ParsedCallRecord[] = [];
  const newSignatures: ProcessedCallSignature[] = [];
  
  for (const record of markedRecords) {
    if (!record.isDuplicate) {
      newRecords.push(record);
      
      // Generate signature for deduplication tracking
      if (record.callDate && record.callTime && record.aniHash) {
        const signature = await generateCallSignature(
          record.callDate,
          record.callTime,
          record.aniHash,
          record.durationSeconds || 0,
          record.callDirection || '',
          record.queueTimeSeconds || 0,
          record.ivrTimeSeconds || 0
        );
        
        if (signature) {
          newSignatures.push({
            id: '', // Will be generated by Supabase
            ani_hash: record.aniHash,
            call_date: record.callDate,
            call_time: record.callTime,
            signature_hash: signature,
            last_upload_id: upload.id,
            processed_at: new Date().toISOString(),
            created_at: new Date().toISOString(),
          });
        }
      }
    }
  }

  // Save call records in batches
  let savedCount = 0;
  const callRecordInserts: CallRecordInsert[] = newRecords.map(r => ({
    upload_id: upload.id,
    call_date: r.callDate,
    call_time: r.callTime,
    call_hour: r.callHour,
    executive: r.executive || 'SIN ATENDER',
    original_call_id: r.originalCallId,
    ani_hash: r.aniHash,
    ani_masked: r.aniMasked,
    call_direction: r.callDirection,
    queue: r.queue,
    duration_seconds: r.durationSeconds,
    duration_formatted: r.durationFormatted,
    attended: r.attended,
    export_complete: r.exportComplete,
    is_overlapping: r.isOverlapping || false,
    queue_time_seconds: r.queueTimeSeconds,
    handle_time_seconds: r.handleTimeSeconds,
    alert_segments: r.alertSegments,
    alert_time_seconds: r.alertTimeSeconds,
    flow_exit: r.flowExit,
    alerted_users: r.alertedUsers,
    users_not_respond: r.usersNotRespond,
    abandon_type: r.abandonType,
    is_bounce: r.isBounce,
    hold_time_seconds: r.holdTimeSeconds,
    acw_seconds: r.acwSeconds,
    ivr_time_seconds: r.ivrTimeSeconds,
    time_to_abandon: r.timeToAbandon,
    exit_reason: r.exitReason,
    abandoned: !r.attended,
  }));

  for (let i = 0; i < callRecordInserts.length; i += BATCH_SIZE) {
    const batch = callRecordInserts.slice(i, i + BATCH_SIZE);
    const { error } = await supabase.from('call_records').insert(batch);
    
    if (error) {
      console.error('Error saving call records batch:', error);
      throw error;
    }
    
    savedCount += batch.length;
  }

  // Save signatures for deduplication tracking
  if (newSignatures.length > 0) {
    for (let i = 0; i < newSignatures.length; i += BATCH_SIZE) {
      const batch = newSignatures.slice(i, i + BATCH_SIZE);
      const { error } = await supabase.from('processed_call_signatures').insert(batch);
      
      if (error) {
        console.error('Error saving signatures:', error);
        // Don't throw here, signatures are for tracking only
      }
    }
  }

  const stats: DeduplicationStats = {
    newRecords: savedCount,
    duplicateRecords: records.length - newRecords.length,
    totalAttempted: records.length,
    canceledOverlappingCalls: canceledCount,
  };

  return { upload, savedCount, stats };
}

// ============================================================================
// DEDUPLICATION / SIGNATURES
// ============================================================================

export async function getProcessedSignatures(): Promise<Set<string>> {
  const { data, error } = await supabase
    .from('processed_call_signatures')
    .select('signature_hash');

  if (error) {
    console.error('Error fetching processed signatures:', error);
    return new Set();
  }

  const signatures = new Set<string>();
  for (const row of data || []) {
    if (row.signature_hash) {
      signatures.add(row.signature_hash);
    }
  }
  
  return signatures;
}

// ============================================================================
// AGENT STATUS
// ============================================================================

export async function getLatestAgentStatusUpload(): Promise<{ upload: AgentStatusUpload; records: AgentStatusRecord[] } | null> {
  const { data: uploadData, error: uploadError } = await supabase
    .from('agent_status_uploads')
    .select('*')
    .order('uploaded_at', { ascending: false })
    .limit(1)
    .single();

  if (uploadError || !uploadData) {
    return null;
  }

  const upload = uploadData as AgentStatusUpload;

  const { data: recordsData, error: recordsError } = await supabase
    .from('agent_status_records')
    .select('*')
    .eq('upload_id', upload.id);

  if (recordsError) {
    console.error('Error fetching agent status records:', recordsError);
    return { upload, records: [] };
  }

  return { upload, records: (recordsData || []) as AgentStatusRecord[] };
}

export async function getAgentStatusRecords(uploadId: string): Promise<AgentStatusRecord[]> {
  const { data, error } = await supabase
    .from('agent_status_records')
    .select('*')
    .eq('upload_id', uploadId);

  if (error) {
    console.error('Error fetching agent status records:', error);
    throw error;
  }

  return data || [];
}

export async function saveAgentStatusUpload(
  filename: string,
  rows: AgentStatusRow[]
): Promise<{ upload: AgentStatusUpload; records: AgentStatusRecord[] }> {
  if (rows.length === 0) {
    throw new Error('No agent status rows to save');
  }

  // Calculate date range
  const dates = rows
    .map(r => r.dateRangeStart)
    .filter((d): d is string => !!d)
    .sort();
  
  const dateRangeStart = dates[0] || null;
  const dateRangeEnd = dates[dates.length - 1] || null;

  // Create upload record
  const { data: uploadData, error: uploadError } = await supabase
    .from('agent_status_uploads')
    .insert({
      filename,
      record_count: rows.length,
      date_range_start: dateRangeStart,
      date_range_end: dateRangeEnd,
    })
    .select()
    .single();

  if (uploadError || !uploadData) {
    console.error('Error creating agent status upload:', uploadError);
    throw uploadError || new Error('Failed to create agent status upload');
  }

  const upload = uploadData as AgentStatusUpload;

  // Save agent status records
  const agentStatusInserts = rows.map(r => ({
    upload_id: upload.id,
    agent_id: r.agentId,
    agent_name: r.agentName,
    date_range_start: r.dateRangeStart,
    date_range_end: r.dateRangeEnd,
    connected_seconds: r.connectedSeconds,
    in_queue_seconds: r.inQueueSeconds,
    out_of_queue_seconds: r.outOfQueueSeconds,
  }));

  const { data: recordsData, error: recordsError } = await supabase
    .from('agent_status_records')
    .insert(agentStatusInserts)
    .select();

  if (recordsError) {
    console.error('Error saving agent status records:', recordsError);
    throw recordsError;
  }

  return { upload, records: (recordsData || []) as AgentStatusRecord[] };
}